#!/bin/bash
# Updated : 1 August 2017
# Wine version : 2.0.2
# Tested on : Ubuntu 16.04, Lubuntu 16.04, Linux Mint 18.1 Cinnamon, elementaryOS, openSUSE Leap 42.2
# v2
# Author : Gyucika91
# Support available on the Revive Network Discord server #support-mac-linux channel!
[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"
 
TITLE="Revive Battlefield 2"
PREFIX="REVIVE_BF2"
POL_System_SetArch "x86"

POL_SetupWindow_Init

# Welcome
POL_SetupWindow_presentation "$TITLE" "Gyucika91" "Unofficial" "Battlelog.co" "$PREFIX"

# Account creation
POL_SetupWindow_question "Do you have an existing Battlelog.co account?\n\nYou need one to play online!\n\nClicking on 'No' will take you to the website to register for an account.\n\nYou may need to close the browser after you have registered in order to continue installation." "Revive Battlefield 2 Account"
if [ "$APP_ANSWER" = "FALSE" ]; then
	POL_Browser 'https://battlelog.co/register.php'
fi

# Create prefix
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "2.0.2"

# Check if p7zip exists
check_one "p7zip" "p7zip"
POL_SetupWindow_missing

# Ask for method of installation
POL_SetupWindow_InstallMethod "LOCAL,DOWNLOAD"

if [ $INSTALL_METHOD = "LOCAL" ]; then

# Use existing setup file
POL_SetupWindow_browse "Find the setup.exe from the Release.zip where you downloaded and extracted it." "Install Revive Battlefield 2"
POL_SetupWindow_wait "Setup is launching..." "Please wait"
POL_Wine start /unix "$APP_ANSWER"
POL_SetupWindow_message "The setup is installing the game.\n\nInstall to the default location.\n\nWhen the installation is complete ONLY select 'Enter license key' and 'Update Punkbuster now'!\n\n         DO NOT SELECT LAUNCH!\n\nAfter you have typed in your CD-key in both places, click 'Apply' and Close'.\nAllow PunkBuster to update, don't worry if anything fails. There is another update after PunkBuster is done, do not accidentally cancel it!\n\nONLY click 'Next' here when the update has finished!" "Revive Battlefield 2 is installing"
else

# Download setup files
POL_Browser 'http://www.mediafire.com/file/372g01paefs5z2v/Release.zip'
POL_SetupWindow_browse "Download and extract Release.zip and return here to locate setup.exe."
POL_SetupWindow_wait "Setup is launching..." "Please wait"
POL_Wine start /unix "$APP_ANSWER"
POL_SetupWindow_message "The setup is installing the game.\n\nInstall to the default location.\n\nWhen the installation is complete ONLY select 'Enter license key' and 'Update Punkbuster now'!\n\n         DO NOT SELECT LAUNCH!\n\nAfter you have typed in your CD-key in both places, click 'Apply' and Close'.\nAllow PunkBuster to update, don't worry if anything fails. There is another update after PunkBuster is done, do not accidentally cancel it!\n\nONLY click 'Next' here when the update has finished!" "Revive Battlefield 2 is installing"
fi

# Install full DirectX 9
POL_Call POL_Install_d3dx9

# Remove previous components and only leave d3dx9_43
POL_Wine reg delete "HKEY_CURRENT_USER\Software\Wine\DllOverrides" "/f"
POL_Wine reg add "HKEY_CURRENT_USER\Software\Wine\DllOverrides" "/v" "d3dx9_43" "/t" "REG_SZ" "/d" "native,builtin" "/f"

# Retrieve current screen resolution of primary/internal monitor for multiple monitor setups
DIMENSIONX=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1 | sed -n '1p')
DIMENSIONY=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2 | sed -n '1p')

# Create temporary folder
POL_System_TmpCreate "$PREFIX"

# Update BF2.exe
POL_SetupWindow_wait "The game client is being updated to the latest available version." "Updating game client"
	cd "$POL_System_TmpDir"
	curl -O "http://download.bf2.us/binary-release/BF2-prod.exe"
	rm -f "$HOME/.PlayOnLinux/wineprefix/$PREFIX/drive_c/Program Files/EA GAMES/Battlefield 2/BF2.exe"
	mv "$POL_System_TmpDir/BF2-prod.exe" "$HOME/.PlayOnLinux/wineprefix/$PREFIX/drive_c/Program Files/EA GAMES/Battlefield 2/BF2.exe"

# Download and merge unlocks.zip
	cd "$POL_System_TmpDir"
	curl -O "http://download.bf2.us/game-release/unlocks.zip"
	7z x "$POL_System_TmpDir/unlocks.zip"
	cp -RT "$POL_System_TmpDir/mods" "$HOME/.PlayOnLinux/wineprefix/$PREFIX/drive_c/Program Files/EA GAMES/Battlefield 2/mods"

# Create shortcut, reason for the word Revive after and not before BF2 is to increase the chance that the find command finds the correct shortcut name!
POL_Shortcut "BF2.exe" "Battlefield 2 Revive" "" "+widescreen 1 +restart 0 +szx $DIMENSIONX +szy $DIMENSIONY"

# Disable winedebug
echo "WINEDEBUG=-all" >> "$HOME/.PlayOnLinux/wineprefix/$PREFIX/playonlinux.cfg"

# Set winecfg
POL_SetupWindow_wait "The configuration is being updated and adjusted to your current screen resolution." "Updating configuration"
Set_Desktop "On" "$DIMENSIONX" "$DIMENSIONY"
POL_Wine_X11Drv "Decorated" "N"
POL_Wine_X11Drv "Managed" "N"
POL_Wine_Direct3D "VideoMemorySize" "512"

# Download and install Special Forces
POL_SetupWindow_question "Do you want to download and install the Special Forces expansion?\n\nIf yes, you will be taken to a link where you can download a rar file.\n\nYou will NOT need to extract the rar file yourself." "Download Special Forces expansion"
if [ "$APP_ANSWER" = "TRUE" ]; then
	POL_Browser 'https://docs.google.com/uc?id=0Bz9nf3wWatLDdExzRkF2S0d2b1U&export=download'
POL_SetupWindow_browse "Find the rar file you have downloaded."
POL_SetupWindow_wait "File is extracting..." "Please wait"
	cd "$POL_System_TmpDir"
	7z x "$APP_ANSWER" -o$POL_System_TmpDir
	mv "$POL_System_TmpDir/xpack" "$HOME/.PlayOnLinux/wineprefix/$PREFIX/drive_c/Program Files/EA GAMES/Battlefield 2/mods"
fi

# Download 64 map SP mode - FUNCTION NOT USED MOD CRASHES
#POL_SetupWindow_question "Do you want to download a 64-player map mod for Singleplayer?" "Battlefield 2 64-player SP mod"
#if [ "$APP_ANSWER" = "TRUE" ]; then
#	cd "$POL_System_TmpDir"
#	curl -O "http://www.mediafire.com/file/vpui868b9j5tyks/BF64SPMOD.7z"
#	mv "$POL_System_TmpDir/BF64SPMOD.7z" "$POL_System_TmpDir/BF64SPMOD"
#MODLINK=$(grep kNO "$POL_System_TmpDir/BF64SPMOD" | sed -n '1p' | cut -d '"' -f2)
#	POL_Download "$MODLINK" "9787fd226ed89d101de4ace8618ecff6"
#	7z e -previvebf2142 "$POL_System_TmpDir/BF64SPMOD.7z"
#	POL_Wine start /unix "$POL_System_TmpDir/bf2all64_v1.0_setup.exe"
#POL_SetupWindow_message "The installer for 64-player map mod for Singleplayer is launching...\n\n\n           Only click 'Next' here when it has finished!" "Installing mod"
#	POL_Shortcut "BF2.exe" "Battlefield 2 64-SP" "" "+widescreen 1 +szx $DIMENSIONX +szy $DIMENSIONY +modPath /mods/bf2all64"
#fi

# Delete temp
POL_System_TmpDelete

# Outro
POL_SetupWindow_message "You are now ready to play!\nFind the shortcut on your desktop or in the PlayOnLinux window.\nLog in using your Battlelog.co username and password.\nSee you on the battlefield!\n\nKNOWN BUG: Under unity desktop on Ubuntu the game may fail to stay full-screen. A workaround is to disable the Virtual Desktop option in winecfg!\n\nJoin the Revive Network Discord server #support-mac-linux channel for help!" "Installation complete!"

POL_SetupWindow_Close
exit
